apiVersion: apps/v1
kind: Deployment
metadata:
  name: DocumentManagement
  labels:
    app: DocumentManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DocumentManagement
  template:
    metadata:
      labels:
        app: DocumentManagement
    spec:
      containers:
        - name: DocumentManagement
          image: "username/DocumentManagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
