name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./CitizenServiceApplication/pom.xml
          mvn clean package -f ./QualificationVerification/pom.xml
          mvn clean package -f ./DocumentManagement/pom.xml

      - name: Docker Build and push for CitizenServiceApplication
        uses: docker/build-push-action@v4
        with:
          context: ./CitizenServiceApplication
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/citizenserviceapplication:latest
            ghcr.io/${{ github.repository }}/citizenserviceapplication:${{ github.ref_name }}
            
      - name: Docker Build and push for QualificationVerification
        uses: docker/build-push-action@v4
        with:
          context: ./QualificationVerification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/qualificationverification:latest
            ghcr.io/${{ github.repository }}/qualificationverification:${{ github.ref_name }}
            
      - name: Docker Build and push for DocumentManagement
        uses: docker/build-push-action@v4
        with:
          context: ./DocumentManagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/documentmanagement:latest
            ghcr.io/${{ github.repository }}/documentmanagement:${{ github.ref_name }}
            
