apiVersion: v1
kind: Service
metadata:
  name: QualificationVerification
  labels:
    app: QualificationVerification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: QualificationVerification