---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CitizenServiceApplication
  labels:
    app: CitizenServiceApplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CitizenServiceApplication
  template:
    metadata:
      labels:
        app: CitizenServiceApplication
    spec:
      containers:
        - name: CitizenServiceApplication
          image: username/CitizenServiceApplication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: QualificationVerification
  labels:
    app: QualificationVerification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: QualificationVerification
  template:
    metadata:
      labels:
        app: QualificationVerification
    spec:
      containers:
        - name: QualificationVerification
          image: username/QualificationVerification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DocumentManagement
  labels:
    app: DocumentManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DocumentManagement
  template:
    metadata:
      labels:
        app: DocumentManagement
    spec:
      containers:
        - name: DocumentManagement
          image: username/DocumentManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: CitizenServiceApplication
  labels:
    app: CitizenServiceApplication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CitizenServiceApplication


---


apiVersion: v1
kind: Service
metadata:
  name: QualificationVerification
  labels:
    app: QualificationVerification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: QualificationVerification


---


apiVersion: v1
kind: Service
metadata:
  name: DocumentManagement
  labels:
    app: DocumentManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DocumentManagement

