apiVersion: v1
kind: Service
metadata:
  name: CitizenServiceApplication
  labels:
    app: CitizenServiceApplication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CitizenServiceApplication